### PR TITLE
Matheo/wip

### PR DESCRIPTION
**Pull request by onmax**
@mraveux I forgot to mention that there is another case, that seems to be broken now:

Clicking on a marker to open the card will result in a weird opening behaviour. See this GIF
https://gyazo.com/ad1162eec50b2e7b0aa4dd01a34088a5

That's what the code from @sisou was doing

### CODE REVIEW

**Comment by mraveux** [comment]
@onmax yes if this is caused by the `scrollIntoView` then we can just go back to the `scrollTo` and `getBoundingClientRect`.

**Comment by Albermonte** [comment]
If you click on a location in the map, then start dragging and release after progress is >50% but not 100%, the same error happens again

https://gyazo.com/d719327cc433c0a9358c466d34e57307

**Comment by onmax** [comment]
Please also check this project:
- https://github.com/emilkowalski/vaul
- With snaps: https://jchtff-3000.csb.app/

**Comment by mraveux** [comment]
I think I found the origin of the issue.
Apparently setting the dynamic padding on the parent element (li) of the SheetModal (article) was conflicting with safari snap’s position calculation. Since the padding on the li and the width of the article were changing at the same time as the snap was trying to center the element, it was creating this issue where everything would end up translated on the side / out of screen.
Setting the padding now on the article directly, and not changing the card width, seems to fix the issue.

**Comment by sisou** [comment]
@mraveux By setting the width to `100vw`, are the cards still able to shrink and show the previous and next partially at the screen edge when not expanded?

**Comment by mraveux** [comment]
Yes @sisou, it should look exactly the same as before.

**Pull request merged**
