### PR TITLE
Matheo/wip

### PR DESCRIPTION
**Pull request by onmax**

### CODE REVIEW

**Comment by sisou** [comment]
@onmax did you test these "fixes" against old behavior we explicitly fixed? E.g. using `scrollIntoView` makes the whole app jump when clicking on a marker on mobile while the list is closed.

**Comment by onmax** [comment]
#4

**Comment by onmax** [comment]
I reset the `v2` branch

**Comment by mraveux** [comment]
If needed we can continue to use `scrollTo` instead of `scrollIntoView`. My goal here was just to not call getBoundingClientRect too much during the expand animation. @sisou

**Pull request merged**
